// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddNodeAPI(arg1:number,arg2:number,arg3:number):Promise<void>;

export function GetNodesAPI():Promise<Array<models.Node>>;

export function Greet(arg1:string):Promise<string>;
