// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMemberAPI(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMemberAPI'](arg1, arg2, arg3);
}

export function AddNodeAPI(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNodeAPI'](arg1, arg2, arg3);
}

export function ClearNodesAPI() {
  return window['go']['main']['App']['ClearNodesAPI']();
}

export function GetMembersAPI() {
  return window['go']['main']['App']['GetMembersAPI']();
}

export function GetNodeAPI(arg1) {
  return window['go']['main']['App']['GetNodeAPI'](arg1);
}

export function GetNodesAPI() {
  return window['go']['main']['App']['GetNodesAPI']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveNodeAPI(arg1) {
  return window['go']['main']['App']['RemoveNodeAPI'](arg1);
}

export function UpdateNodeAPI(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNodeAPI'](arg1, arg2, arg3);
}
