// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddMemberAPI(arg1:number,arg2:number,arg3:number):Promise<void>;

export function AddNodeAPI(arg1:number,arg2:number,arg3:number):Promise<void>;

export function ClearNodesAPI():Promise<void>;

export function GetMembersAPI():Promise<Array<models.Member>>;

export function GetNodeAPI(arg1:number):Promise<models.Node>;

export function GetNodesAPI():Promise<Array<models.Node>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveNodeAPI(arg1:number):Promise<void>;

export function UpdateNodeAPI(arg1:number,arg2:number,arg3:number):Promise<void>;
