// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNodeAPI(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNodeAPI'](arg1, arg2, arg3);
}

export function GetNodesAPI() {
  return window['go']['main']['App']['GetNodesAPI']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
